### ISSUE TITLE
aiostalk is broken as greenstalk release 2.0.2

### ISSUE THREAD

**Issue by yichuanxiong** [koodaamo/aiostalk#5]
Hi,

I'm seeing this error when trying to import aiostalk

```
Python 3.8.10 (default, Mar 13 2023, 10:26:41)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiostalk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/madmin/venv/connectors3/lib/python3.8/site-packages/aiostalk.py", line 5, in <module>
    from greenstalk import _parse_response, _parse_chunk, _parse_simple_yaml, _parse_simple_yaml_list, _to_id
ImportError: cannot import name '_parse_simple_yaml' from 'greenstalk' (/home/madmin/venv/connectors3/lib/python3.8/site-packages/greenstalk/__init__.py)
```
I fixed it by manually install `greenstalk==2.0.0`

Do we have a plan to fix it in aiostalk as well?

Thanks.

**Comment by petri** [comment]
Thank you for the report. Could you submit a pull request with a fix? I'd prefer not requiring an older version of greenstalk.

**Comment by petri** [comment]
please upgrade to 1.2 that should have this fixed now
